[fraud-detection] fix dropped gRPC service files in shadow jar (#3501)
* [fraud-detection] fix dropped gRPC service files in shadow jar

Shadow 9 defaults duplicatesStrategy to EXCLUDE, which drops duplicate
META-INF/services files before mergeServiceFiles() can merge them. As a
result the DNS name resolver registration from grpc-core was lost and
gRPC fell back to the unix scheme as default, breaking the flagd
provider connection:

  GenericConfigException: Error with gRPC target string configuration
  Caused by: IllegalArgumentException: Address types of NameResolver
  'unix' for 'unix:///localhost:8013' not supported by transport

Regression introduced by the Shadow 8.1.1 -> 9.4.2 bump in 36e2ce4d.
Setting duplicatesStrategy to INCLUDE restores service file merging,
as recommended by the Shadow 9.0.1 release notes.

See https://github.com/GradleUp/shadow/issues/1348 and
https://github.com/grpc/grpc-java/issues/12282

Signed-off-by: Simon Schrottner <simon.schrottner@gmail.com>

* [fraud-detection] add changelog entry for #3501

Signed-off-by: Simon Schrottner <simon.schrottner@gmail.com>

---------

Signed-off-by: Simon Schrottner <simon.schrottner@gmail.com>